import WhiteLabelHeader from "../components/WhiteLabelHeader.jsx";
import PropertyFacts from "../components/PropertyFacts.jsx";
import MarketConditions from "../components/MarketConditions.jsx";
import LoanCalculator from "../components/LoanCalculator.jsx";
import AISummary from "../components/AISummary.jsx";
import ShareExport from "../components/ShareExport.jsx";
import {
  MOCK_PROPERTY,
  MOCK_MARKET,
  MOCK_AI_RESPONSE,
} from "../data/mockData.js";

function BackButton({ onClick }) {
  return (
    <button
      type="button"
      onClick={onClick}
      style={{
        display: "inline-flex",
        alignItems: "center",
        gap: 6,
        height: 30,
        padding: "0 12px",
        background: "var(--card)",
        color: "var(--muted-soft)",
        border: "1px solid var(--border)",
        borderRadius: 7,
        fontFamily: "var(--font-sans)",
        fontSize: 12,
        fontWeight: 600,
        cursor: "pointer",
        transition: "color 0.15s ease, border-color 0.15s ease",
      }}
      onMouseEnter={(e) => {
        e.currentTarget.style.color = "var(--white)";
        e.currentTarget.style.borderColor = "var(--muted)";
      }}
      onMouseLeave={(e) => {
        e.currentTarget.style.color = "var(--muted-soft)";
        e.currentTarget.style.borderColor = "var(--border)";
      }}
    >
      <span aria-hidden="true">←</span>
      Back to chat
    </button>
  );
}

function PropertyHeader({ property }) {
  const stats = [
    { label: "Beds", value: property.beds },
    { label: "Baths", value: property.baths },
    { label: "Sq ft", value: property.sqft?.toLocaleString() },
    { label: "Lot", value: property.lotSize },
    { label: "Year", value: property.yearBuilt },
    { label: "Status", value: property.listingStatus },
  ];

  return (
    <section
      style={{
        background: "var(--card)",
        border: "1px solid var(--border)",
        borderRadius: 12,
        padding: 24,
        marginBottom: 16,
      }}
    >
      <h1
        style={{
          fontFamily: "var(--font-sans)",
          fontWeight: 800,
          fontSize: 30,
          color: "var(--white)",
          letterSpacing: "-0.02em",
          lineHeight: 1.1,
          marginBottom: 4,
        }}
      >
        {property.address}
      </h1>
      <p
        style={{
          fontFamily: "var(--font-sans)",
          fontSize: 14,
          color: "var(--muted)",
          marginBottom: 20,
        }}
      >
        {property.city}, {property.state} {property.zip}
      </p>
      <div
        style={{
          display: "grid",
          gridTemplateColumns: "repeat(6, 1fr)",
          gap: 8,
        }}
      >
        {stats.map((s) => (
          <div
            key={s.label}
            style={{
              padding: 12,
              background: "var(--border-soft)",
              border: "1px solid var(--border)",
              borderRadius: 10,
              display: "flex",
              flexDirection: "column",
              gap: 4,
              minWidth: 0,
            }}
          >
            <span
              style={{
                fontFamily: "var(--font-mono)",
                fontSize: 9,
                color: "var(--muted)",
                letterSpacing: "0.1em",
                textTransform: "uppercase",
              }}
            >
              {s.label}
            </span>
            <span
              style={{
                fontFamily: "var(--font-mono)",
                fontSize: 16,
                fontWeight: 700,
                color: "var(--white)",
                overflow: "hidden",
                textOverflow: "ellipsis",
                whiteSpace: "nowrap",
              }}
            >
              {s.value ?? "—"}
            </span>
          </div>
        ))}
      </div>
    </section>
  );
}

function LegalFooter() {
  return (
    <footer
      style={{
        marginTop: 8,
        padding: "16px 4px",
        fontFamily: "var(--font-sans)",
        fontSize: 12,
        color: "var(--muted)",
        lineHeight: 1.5,
        textAlign: "center",
      }}
    >
      Generated by Vis · vis.realestate — for informational purposes only,
      not financial or legal advice.
    </footer>
  );
}

function PropertyReport({ data, onBack }) {
  // Session 8 uses full mock data sources. The `data` prop (passed in
  // from the Generate Full Report button) is the inline card data —
  // future sessions can hydrate the report from it. For now we render
  // the full mock so each section is meaningfully populated.
  const property = MOCK_PROPERTY;
  const market = MOCK_MARKET;
  const ai = MOCK_AI_RESPONSE;

  return (
    <div
      style={{
        flex: 1,
        display: "flex",
        flexDirection: "column",
        background: "var(--bg)",
        overflow: "auto",
      }}
    >
      <div
        style={{
          display: "flex",
          alignItems: "center",
          gap: 16,
          padding: "16px 20px",
          borderBottom: "1px solid var(--border)",
          position: "sticky",
          top: 0,
          background: "var(--bg)",
          zIndex: 5,
        }}
      >
        <BackButton onClick={onBack} />
        <span
          style={{
            fontFamily: "var(--font-mono)",
            fontSize: 11,
            color: "var(--muted)",
            letterSpacing: "0.1em",
            textTransform: "uppercase",
          }}
        >
          Property Report
        </span>
      </div>

      <main
        style={{
          flex: 1,
          padding: "20px",
          width: "100%",
          maxWidth: 960,
          margin: "0 auto",
        }}
      >
        <WhiteLabelHeader reportType="Property Report" />
        <PropertyHeader property={property} />
        <PropertyFacts property={property} />
        <MarketConditions market={market} />
        <LoanCalculator />
        <AISummary
          summary={ai.aiSummary}
          strengths={ai.keyStrengths}
          risks={ai.keyRisks}
          bestSuitedFor={ai.bestSuitedFor}
        />
        <ShareExport />
        <LegalFooter />
      </main>
    </div>
  );
}

export default PropertyReport;
